# Generated by Django 5.2.14 on 2026-05-30

import os
from datetime import datetime, timezone

from django.db import migrations, models


def seed_home_content(apps, schema_editor):
    CourseResource = apps.get_model("announcements", "CourseResource")
    HomeAssignment = apps.get_model("announcements", "HomeAssignment")
    NewsPost = apps.get_model("announcements", "NewsPost")

    if not NewsPost.objects.exists():
        NewsPost.objects.bulk_create(
            [
                NewsPost(
                    title="Assignment 2 test cases updated",
                    text="Please re-submit if you failed hidden case #4.",
                    created_when=datetime(2026, 4, 10, 12, 0, tzinfo=timezone.utc),
                ),
                NewsPost(
                    title="Welcome to Spring 2026",
                    text="Please review the Course Syllabus before our first lecture.",
                    created_when=datetime(2026, 4, 1, 12, 0, tzinfo=timezone.utc),
                ),
            ]
        )

    if not HomeAssignment.objects.exists():
        HomeAssignment.objects.bulk_create(
            [
                HomeAssignment(
                    title="Assignment 3: Graph Coloring Problem",
                    description="Due: May 15, 2026, 11:59 PM • Max Score: 100 pts",
                    status_label="Active",
                    status_tone="active",
                    icon="keyboard outline",
                    order=1,
                ),
                HomeAssignment(
                    title="Assignment 2: Traveling Salesperson (TSP)",
                    description="Due: April 30, 2026, 11:59 PM • Max Score: 100 pts",
                    status_label="Active",
                    status_tone="active",
                    icon="keyboard outline",
                    order=2,
                ),
                HomeAssignment(
                    title="Assignment 1: Knapsack Problem",
                    description="Ended: Mar 10, 2026 • Graded",
                    status_label="Closed",
                    status_tone="closed",
                    icon="check circle outline",
                    order=3,
                ),
            ]
        )

    if not CourseResource.objects.exists():
        shared_box_url = os.environ.get("COURSE_RESOURCES_BOX_URL", "").strip()
        resources = [
            ("Course Syllabus", "file pdf outline", "#db2828", "COURSE_SYLLABUS_URL"),
            ("Lecture Slides & Notes", "file powerpoint outline", "#f2711c", "COURSE_SLIDES_URL"),
            ("Starter Code Templates", "github", "#1b1c1d", "COURSE_STARTER_CODE_URL"),
            ("Discussion Forum", "comments outline", "#2185d0", "COURSE_FORUM_URL"),
        ]
        CourseResource.objects.bulk_create(
            [
                CourseResource(
                    title=title,
                    icon=icon,
                    color=color,
                    url=os.environ.get(url_env, "").strip() or shared_box_url,
                    order=index,
                )
                for index, (title, icon, color, url_env) in enumerate(resources, start=1)
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_alter_announcement_id_alter_newspost_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("icon", models.CharField(default="file outline", max_length=80)),
                ("color", models.CharField(default="#1a364d", max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("status_label", models.CharField(default="Active", max_length=40)),
                (
                    "status_tone",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="keyboard outline", max_length=80)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(seed_home_content, migrations.RunPython.noop),
    ]
